import SiteNav from "@/components/SiteNav";
import "./globals.css";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";

const myFont = localFont({
  src: "../../public/fonts/avenir_roman_12.woff",
  variable: "--font-avenir",
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  preload: false,
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${myFont.variable}`}>
        <SiteNav />
        {children}
      </body>
    </html>
  );
}
